### ISSUE TITLE
Exception due not evaluating RegValueKind.None

### ISSUE THREAD

**Issue by ElektroStudios** [cyotek/RegistryComparer#1]
The program throws a exception at **RegistrySnapshotBuilder.GetDefaultValue()** function when attempting to create a snapshot, when a registry value of kind **RegistryValueKind.None** is found. This can be avoided by adding a case for **RegistryValueKind.None** inside the same method block, but I'm not sure about its consequences when doing that.

**Comment by cyotek** [comment]
Hello,

Thanks for the bug report! Off the top of my head I can't remember if it will have any impact either, but it should be safe change. I'll try and get a moment to test it and commit a fix.

Regards;
Richard Moss

**Comment by cyotek** [comment]
Hello,

I've updated the tool with a fix - thanks again for finding it. I also fixed a new crash bug I found while running a scan on my current system.

Note that the original project was using .NET 3.5, which didn't have support for `REG_NONE` at all it seems... I've upgraded it to 4.6 as my usual common version.

Regards;
Richard Moss
